import { ILevel } from "./types"

export const levels:ILevel[] = [
  // {
  //   id: 1,
  //   name: 'test',
  //   words: [
  //     {
  //       word: 'Саар',
  //       question: "Ріка у Франції і Німеччині, права притока ріки Мозель",
  //       xStart: 0,
  //       yStart: 0,
  //       vertical: false,
  //       index: '1',
  //     },
  //     {
  //       word: 'Стометрівка',
  //       question: "Дистанція сто метрів у спортивних змаганнях з бігу, плавання тощо",
  //       xStart: 0,
  //       yStart: 0,
  //       vertical: true,
  //       index: '1',
  //     },
  //     {
  //       word: 'Ар',
  //       question: "Міра земельної площі",
  //       xStart: 1,
  //       yStart: 0,
  //       vertical: true,
  //       index: '2',
  //     },
  //     {
  //       word: 'Аав',
  //       question: "... Евальд (естонський композитор)",
  //       xStart: 2,
  //       yStart: 0,
  //       vertical: true,
  //       index: '3',
  //     },
  //     {
  //       word: 'Рвач',
  //       question: "Той, хто намагається одержати за свою працю більше, ніж вона варта",
  //       xStart: 3,
  //       yStart: 0,
  //       vertical: true,
  //       index: '4',
  //     },
  //     {
  //       word: 'Троп',
  //       question: "Узагальнююча назва літературно-музичних жанрів в середньовічній західній Європі, в основі яких лежить поетична або музично-поетична обробка створених раніше григоріанських розспівів.",
  //       xStart: 5,
  //       yStart: 0,
  //       vertical: true,
  //       index: '5',
  //     },
  //     {
  //       word: 'Тама',
  //       question: "Річка в регіоні Канто, в Японії.",
  //       xStart: 5,
  //       yStart: 0,
  //       vertical: false,
  //       index: '5',
  //     },
  //     {
  //       word: 'Атн',
  //       question: "Академія технологічних наук",
  //       xStart: 6,
  //       yStart: 0,
  //       vertical: true,
  //       index: '6',
  //     },
  //     {
  //       word: 'Ми',
  //       question: "Я і ти",
  //       xStart: 7,
  //       yStart: 0,
  //       vertical: true,
  //       index: '7',
  //     },
  //     {
  //       word: 'Анкілостома',
  //       question: "Збудник анкілостомозу",
  //       xStart: 8,
  //       yStart: 0,
  //       vertical: true,
  //       index: '8',
  //     },
  //   ],
  // },
  {
    id: 1,
    name: '№1',
    words: [
      {
        word: 'Зів',
        question: "Вхід з порожнини рота в глотку",
        xStart: 0,
        yStart: 0,
        vertical: false,
        index: '1',
      },
      {
        word: 'Сад',
        question: "Багато плодових дерев",
        xStart: 6,
        yStart: 0,
        vertical: false,
        index: '4',
      },
      {
        word: 'Олово',
        question: "М'який, легкий метал сріблясто-білого кольору (Sn)",
        xStart: 2,
        yStart: 1,
        vertical: false,
        index: '6',
      },
      {
        word: 'Кар',
        question: "Двадцять четверта літера грузинської абетки",
        xStart: 0,
        yStart: 2,
        vertical: false,
        index: '7',
      },
      {
        word: 'Зал',
        question: "Велике приміщення для багатолюдних зборів",
        xStart: 6,
        yStart: 2,
        vertical: false,
        index: '8',
      },
      {
        word: 'Впаювання',
        question: "Закріплення паянням чого-небудь у чомусь",
        xStart: 0,
        yStart: 4,
        vertical: false,
        index: '9',
      },
      {
        word: 'Океанолог',
        question: "Фахівець з океанології",
        xStart: 0,
        yStart: 6,
        vertical: false,
        index: '14',
      },
      {
        word: 'Зло',
        question: "Протилежне добру",
        xStart: 0,
        yStart: 8,
        vertical: false,
        index: '19',
      },
      {
        word: 'Вад',
        question: "Спільна назва мінералів — землистих сумішей гідроксидів марганцю",
        xStart: 6,
        yStart: 8,
        vertical: false,
        index: '20',
      },
      {
        word: 'Радар',
        question: "Те саме, що радіолокатор",
        xStart: 2,
        yStart: 9,
        vertical: false,
        index: '21',
      },
      {
        word: 'Сша',
        question: "Сполучені Штати",
        xStart: 0,
        yStart: 10,
        vertical: false,
        index: '22',
      },
      {
        word: 'Ася',
        question: "Художній фільм режисера Олександра Іванівського (кіностудія «Радянське кіно», 1928 р.)",
        xStart: 6,
        yStart: 10,
        vertical: false,
        index: '23',
      },
      {
        word: 'Заков',
        question: "Актор, який зіграв Уерлі у фільмі «Звіробій» (Союзтелефільм, 1990)",
        xStart: 0,
        yStart: 0,
        vertical: true,
        index: '1',
      },
      {
        word: 'Ворса',
        question: "Густий пушок з коротких волокон на поверхні деяких тканин",
        xStart: 2,
        yStart: 0,
        vertical: true,
        index: '2',
      },
      {
        word: 'Норов',
        question: "Сукупність душевних якостей людини, які проявляються в її діях, поведінці",
        xStart: 4,
        yStart: 0,
        vertical: true,
        index: '3',
      },
      {
        word: 'Созон',
        question: "Муніципалітет у Франції, у регіоні Бретань, департамент Морбіан",
        xStart: 6,
        yStart: 0,
        vertical: true,
        index: '4',
      },
      {
        word: 'Далія',
        question: "Нохія у Сирії, що входить до складу району Джебла провінції Латакія",
        xStart: 8,
        yStart: 0,
        vertical: true,
        index: '5',
      },
      {
        word: 'Пак',
        question: "Ще б ...!",
        xStart: 1,
        yStart: 4,
        vertical: true,
        index: '10',
      },
      {
        word: 'Юта',
        question: "Штат у США",
        xStart: 3,
        yStart: 4,
        vertical: true,
        index: '11',
      },
      {
        word: 'Або',
        question: "Розділовий сполучник",
        xStart: 5,
        yStart: 4,
        vertical: true,
        index: '12',
      },
      {
        word: 'Нло',
        question: "Неопізнаний літаючий об'єкт",
        xStart: 7,
        yStart: 4,
        vertical: true,
        index: '13',
      },
      {
        word: 'Оазис',
        question: "Родюче місце в пустелі або напівпустелі з буйною рослинністю і прісною водою",
        xStart: 0,
        yStart: 6,
        vertical: true,
        index: '14',
      },
      {
        word: 'Евора',
        question: "Місто на сході Португалії, центр однойменного округу та муніципалітету",
        xStart: 2,
        yStart: 6,
        vertical: true,
        index: '15',
      },
      {
        word: 'Найда',
        question: "Те саме, що знайда",
        xStart: 4,
        yStart: 6,
        vertical: true,
        index: '16',
      },
      {
        word: 'Лавра',
        question: "Києво-Печерська ....",
        xStart: 6,
        yStart: 6,
        vertical: true,
        index: '17',
      },
      {
        word: 'Гаддя',
        question: "Гад (збірне)",
        xStart: 8,
        yStart: 6,
        vertical: true,
        index: '18',
      },
    ],
  },
  {
    id: 6,
    name: '№6',
    words: [
      {
        word: 'Десантник',
        question: "Боєць десантної групи, учасник десанту",
        xStart: 0,
        yStart: 0,
        vertical: false,
        index: '1',
      },
      {
        word: 'Авіамотор',
        question: "Двигун літака, вертольота",
        xStart: 0,
        yStart: 2,
        vertical: false,
        index: '5',
      },
      {
        word: 'Дотеп',
        question: "Кмітливий влучний вислів із сатиричним або жартівливим відтінком",
        xStart: 2,
        yStart: 4,
        vertical: false,
        index: '9',
      },
      {
        word: 'Кво',
        question: "Київський військовий округ",
        xStart: 0,
        yStart: 5,
        vertical: false,
        index: '10',
      },
      {
        word: 'Око',
        question: "Орган зору",
        xStart: 6,
        yStart: 5,
        vertical: false,
        index: '11',
      },
      {
        word: 'Латач',
        question: "Місце на мілководді, обладнане для купання дітей",
        xStart: 2,
        yStart: 6,
        vertical: false,
        index: '12',
      },
      {
        word: 'Логістика',
        question: "Розділ математики, що обґрунтовує логіку математичними методами і досліджує її можливості в конструюванні, інформатиці і т. ін. ",
        xStart: 0,
        yStart: 8,
        vertical: false,
        index: '14',
      },
      {
        word: 'Гайдамака',
        question: "Учасник народно-визвольної боротьби",
        xStart: 0,
        yStart: 10,
        vertical: false,
        index: '17',
      },
      {
        word: 'Діалектолог',
        question: "Фахівець із діалектології",
        xStart: 0,
        yStart: 0,
        vertical: true,
        index: '1',
      },
      {
        word: 'Ара',
        question: "Група довгохвостих папуг",
        xStart: 3,
        yStart: 0,
        vertical: true,
        index: '2',
      },
      {
        word: 'Тло',
        question: "Фон",
        xStart: 5,
        yStart: 0,
        vertical: true,
        index: '3',
      },
      {
        word: 'Кардіограма',
        question: "Крива лінія, яка відбиває зміни будь-якого показника функції серця",
        xStart: 8,
        yStart: 0,
        vertical: true,
        index: '4',
      },
      {
        word: 'Індолог',
        question: "Фахівець з індології",
        xStart: 2,
        yStart: 2,
        vertical: true,
        index: '6',
      },
      {
        word: 'Мат',
        question: "Положення в шаховій партії, за якого король, що перебуває під ударом фігури супротивника, не може захиститися, і партія вважається програною",
        xStart: 4,
        yStart: 2,
        vertical: true,
        index: '7',
      },
      {
        word: 'Тапочки',
        question: "Легкі домашні або спортивні туфлі переважно без підборів",
        xStart: 6,
        yStart: 2,
        vertical: true,
        index: '8',
      },
      {
        word: 'Тис',
        question: "Хвойне вічнозелене дерево або чагарник із твердою бурувато-червоною деревиною",
        xStart: 4,
        yStart: 6,
        vertical: true,
        index: '13',
      },
      {
        word: 'Інд',
        question: "Річка в Південній Азії, яка витікає з Тибету й впадає в Індійський океан",
        xStart: 3,
        yStart: 8,
        vertical: true,
        index: '15',
      },
      {
        word: 'Том',
        question: "Частина якого-небудь твору, збірки творів, видання, яка становить окрему книжку",
        xStart: 5,
        yStart: 8,
        vertical: true,
        index: '16',
      },
    ],
  },
];