import { ILevel } from "./types"

export const levels:ILevel[] = [
  // {
  //   id: 1,
  //   name: 'test',
  //   words: [
  //     {
  //       word: 'Саар',
  //       question: "Ріка у Франції і Німеччині, права притока ріки Мозель",
  //       xStart: 0,
  //       yStart: 0,
  //       vertical: false,
  //       index: '1',
  //     },
  //     {
  //       word: 'Стометрівка',
  //       question: "Дистанція сто метрів у спортивних змаганнях з бігу, плавання тощо",
  //       xStart: 0,
  //       yStart: 0,
  //       vertical: true,
  //       index: '1',
  //     },
  //     {
  //       word: 'Ар',
  //       question: "Міра земельної площі",
  //       xStart: 1,
  //       yStart: 0,
  //       vertical: true,
  //       index: '2',
  //     },
  //     {
  //       word: 'Аав',
  //       question: "... Евальд (естонський композитор)",
  //       xStart: 2,
  //       yStart: 0,
  //       vertical: true,
  //       index: '3',
  //     },
  //     {
  //       word: 'Рвач',
  //       question: "Той, хто намагається одержати за свою працю більше, ніж вона варта",
  //       xStart: 3,
  //       yStart: 0,
  //       vertical: true,
  //       index: '4',
  //     },
  //     {
  //       word: 'Троп',
  //       question: "Узагальнююча назва літературно-музичних жанрів в середньовічній західній Європі, в основі яких лежить поетична або музично-поетична обробка створених раніше григоріанських розспівів.",
  //       xStart: 5,
  //       yStart: 0,
  //       vertical: true,
  //       index: '5',
  //     },
  //     {
  //       word: 'Тама',
  //       question: "Річка в регіоні Канто, в Японії.",
  //       xStart: 5,
  //       yStart: 0,
  //       vertical: false,
  //       index: '5',
  //     },
  //     {
  //       word: 'Атн',
  //       question: "Академія технологічних наук",
  //       xStart: 6,
  //       yStart: 0,
  //       vertical: true,
  //       index: '6',
  //     },
  //     {
  //       word: 'Ми',
  //       question: "Я і ти",
  //       xStart: 7,
  //       yStart: 0,
  //       vertical: true,
  //       index: '7',
  //     },
  //     {
  //       word: 'Анкілостома',
  //       question: "Збудник анкілостомозу",
  //       xStart: 8,
  //       yStart: 0,
  //       vertical: true,
  //       index: '8',
  //     },
  //   ],
  // },
  {
    id: 6,
    name: '№6',
    words: [
      {
        word: 'Десантник',
        question: "Боєць десантної групи, учасник десанту",
        xStart: 0,
        yStart: 0,
        vertical: false,
        index: '1',
      },
      {
        word: 'Авіамотор',
        question: "Двигун літака, вертольота",
        xStart: 0,
        yStart: 2,
        vertical: false,
        index: '5',
      },
      {
        word: 'Дотеп',
        question: "Кмітливий влучний вислів із сатиричним або жартівливим відтінком",
        xStart: 2,
        yStart: 4,
        vertical: false,
        index: '9',
      },
      {
        word: 'Кво',
        question: "Київський військовий округ",
        xStart: 0,
        yStart: 5,
        vertical: false,
        index: '10',
      },
      {
        word: 'Око',
        question: "Орган зору",
        xStart: 6,
        yStart: 5,
        vertical: false,
        index: '11',
      },
      {
        word: 'Латач',
        question: "Місце на мілководді, обладнане для купання дітей",
        xStart: 2,
        yStart: 6,
        vertical: false,
        index: '12',
      },
      {
        word: 'Логістика',
        question: "Розділ математики, що обґрунтовує логіку математичними методами і досліджує її можливості в конструюванні, інформатиці і т. ін. ",
        xStart: 0,
        yStart: 8,
        vertical: false,
        index: '14',
      },
      {
        word: 'Гайдамака',
        question: "Учасник народно-визвольної боротьби",
        xStart: 0,
        yStart: 10,
        vertical: false,
        index: '17',
      },
      {
        word: 'Діалектолог',
        question: "Фахівець із діалектології",
        xStart: 0,
        yStart: 0,
        vertical: true,
        index: '1',
      },
      {
        word: 'Ара',
        question: "Група довгохвостих папуг",
        xStart: 3,
        yStart: 0,
        vertical: true,
        index: '2',
      },
      {
        word: 'Тло',
        question: "Фон",
        xStart: 5,
        yStart: 0,
        vertical: true,
        index: '3',
      },
      {
        word: 'Кардіограма',
        question: "Крива лінія, яка відбиває зміни будь-якого показника функції серця",
        xStart: 8,
        yStart: 0,
        vertical: true,
        index: '4',
      },
      {
        word: 'Індолог',
        question: "Фахівець з індології",
        xStart: 2,
        yStart: 2,
        vertical: true,
        index: '6',
      },
      {
        word: 'Мат',
        question: "Положення в шаховій партії, за якого король, що перебуває під ударом фігури супротивника, не може захиститися, і партія вважається програною",
        xStart: 4,
        yStart: 2,
        vertical: true,
        index: '7',
      },
      {
        word: 'Тапочки',
        question: "Легкі домашні або спортивні туфлі переважно без підборів",
        xStart: 6,
        yStart: 2,
        vertical: true,
        index: '8',
      },
      {
        word: 'Тис',
        question: "Хвойне вічнозелене дерево або чагарник із твердою бурувато-червоною деревиною",
        xStart: 4,
        yStart: 6,
        vertical: true,
        index: '13',
      },
      {
        word: 'Інд',
        question: "Річка в Південній Азії, яка витікає з Тибету й впадає в Індійський океан",
        xStart: 3,
        yStart: 8,
        vertical: true,
        index: '15',
      },
      {
        word: 'Том',
        question: "Частина якого-небудь твору, збірки творів, видання, яка становить окрему книжку",
        xStart: 5,
        yStart: 8,
        vertical: true,
        index: '16',
      },
    ],
  },
];